name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: [cron: 30 12 * * 3, cron: 0 22 * * 5]
    

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [11, 57, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'

      - name: Add permition to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Tests
        run: ./gradlew test
